config/routes.rb
Rails.application.routes.draw do
  get "messages/create"
  get "pages/home"
  resource :session
  resources :passwords, param: :token
  resource :registration, only: %i[new create]
  resources :chatrooms, only: %i[new create show index] do
    resources :messages, only: :create
  end
  get "manage_chatrooms", to: "chatrooms#manage"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :user
  belongs_to :chatroom
  validates :body, length: { maximum: 300 }
  after_create_commit -> {
    broadcast_append_to chatroom,
      target: dom_id(chatroom, :messages),
      partial: "messages/message",
      locals: { message: self }
  }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user = Current.user
    if @chatroom.save
      redirect_to chatroom_path(@chatroom), notice: "Congrats for your new chatroom!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @messages = Message.where(chatroom: @chatroom).last(100)
    @message = @chatroom.messages.build
    @active_users, @idle_users = PresenceRoster.build(@chatroom.id)
  end

  def index
    @chatrooms = Chatroom.all.order(created_at: :desc)
    @user_chatrooms = Chatroom.where(user: Current.user)
  end

  private

  def chatroom_params
   params.require(:chatroom).permit(:name)
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = Current.user
    if @message.save
      redirect_to chatroom_path(@chatroom), notice: "Saved message"
    else
      render "chatrooms/show", status: :unprocessable_content
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to root_path, notice: "You are now signed up!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/chatrooms/_active.html.erb
<div class="presence">
  <div class="presence-row">
    <strong>Active (<%= @active_users&.size %>)</strong>
    <ul>
      <% @active_users&.each do |u| %>
        <li><%= u.email_address %></li>
      <% end %>
    </ul>
  </div>

  <div class="presence-row">
    <strong>Idle (<%= @idle_users&.size || 0 %>)</strong>
    <ul>
      <% @idle_users&.each do |u| %>
        <li><%= u.email_address %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/chatrooms/index.html.erb
<%= render "shared/navbar"%>
<div class="container">
  <h1>Browse chatrooms</h1>
  <div class="infobox">
  You have created <%= @user_chatrooms.count%> chatrooms, to only show yours click <%= link_to "here", manage_chatrooms_path%>!
  </div>

  <% @chatrooms.each do |chatroom| %>
    <a class="chatroom-list-element" href=<%= chatroom_path(chatroom) %>>
      <strong><%= chatroom.name %></strong> created by <i> <%= chatroom.user.email_address%></i>  - <%= time_ago_in_words(chatroom.created_at) %> ago
    </a>
  <%end%>
</div>

app/views/chatrooms/new.html.erb
<%= render "shared/navbar"%>
<h1>Create a new chatroom </h1>
<div class="infobox">
  On this page you can create your own, custom chatroom! Right now, we have <strong><%= Chatroom.count%> </strong>
  created and a total of <%= User.count%> users registered on site!
</div>

<% if @chatroom.errors.any? %>
  <div class="error-box">
    <h2><%= pluralize(@chatroom.errors.count, "error") %> prevented this chatroom from being saved:</h2>
    <ul>
      <% @chatroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @chatroom, class: "form-chatroom" do |form| %>
  <%= form.label "Chatroom Name", class: "chatroom-label"%> <br>
  <%= form.text_field :name, class: "chatroom-input", required: true, autofocus: true, placeholder: "A fancy name for your chatroom"%><br>
  <%= form.submit "Create chatroom", class: "submit-btn"%>
<%end%>

app/views/chatrooms/show.html.erb
<%= render "shared/navbar"%>
<%= turbo_stream_from @chatroom %>
<div data-chat-room-id="<%= @chatroom.id %>" class="container" data-controller="chatroom" >
  <h1><%= @chatroom.name %></h1>
  <div class="chatbox" id="<%= dom_id(@chatroom, :messages)%>">
    <%= render @messages%>
  </div>
  <div class="active-users" id="<%= dom_id(@chatroom)%>">
    <%= render 'chatrooms/active' %>
  </div>
  <%= form_with model: [@chatroom, @message], class: "new-message" do |form| %>
    <%= form.text_area :body, data: {"chatroom-target": "message", "action": "input->chatroom#update"}%>
    <%= form.submit "Send", data: {"chatroom-target": "submit"},  class: "submit-message"%>
  <% end %>
  <p data-chatroom-target="characters">  </p>
  <audio id="message-sound" hidden src="<%= audio_path("message.mp3")%>"></audio>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rchat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body  data-current-user-id="<%= Current.user.id %>">
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div data-controller="message" data-user-id="<%= message.user_id %>">
  <div class="author"><%= message.user.email_address%> － <%= time_ago_in_words(message.created_at) %> ago</div>
  <%= message.body %>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/pages/home.html.erb
<%= render "shared/navbar"%>

<div class="container">
  <div class="home-message">
    <h1 class="h1-home">
        <h1> Welcome back, <%= Current.user.email_address %></h1>
    </h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-right">
    <%= link_to "Home", root_path,  class: "navlink" %>
    <%= link_to "New Chatroom", new_chatroom_path,  class: "navlink" %>
    <%= link_to "Chatrooms", chatrooms_path,  class: "navlink" %>
    <%= link_to "My Stats", root_path,  class: "navlink" %>
      <%= link_to 'Logout', session_path, class: "navlink", method: :delete, data: {turbo_method: :delete} %>
  </div>
</nav>